# 11. 데이터 분석을 위한 패키지

## 01) 배열 데이터를 효과적으로 다루는 Numpy

## 배열생성하기

### 시퀀스 데이터로부터 배열 생성

In [1]:
import numpy as np

In [2]:
# arr_obj = np.array(seq_data)
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [32]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2 # 정수와 실수가 혼합돼 있을 때는 모두 실수로 변환

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [33]:
type(a2)

numpy.ndarray

In [4]:
a1.dtype

dtype('int32')

In [5]:
a2.dtype

dtype('float64')

In [6]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [8]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 범위를 지정해 배열 생성

In [14]:
# arr_obj = np.arange([start,] stop[, step])
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(12).reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
b = np.arange(12)
c = b.reshape(3, 4)

In [22]:
c.shape

(3, 4)

In [23]:
d = np.arange(5)
d.shape

(5,)

In [24]:
# arr_obj = np.linspace(start, stop[, num]) # 시작과 끝 사이에 일정한 간격을 갖는 num개의 요소 생성
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
np.linspace(1, np.pi, 20)

array([1.        , 1.1127154 , 1.22543081, 1.33814621, 1.45086161,
       1.56357701, 1.67629242, 1.78900782, 1.90172322, 2.01443863,
       2.12715403, 2.23986943, 2.35258483, 2.46530024, 2.57801564,
       2.69073104, 2.80344645, 2.91616185, 3.02887725, 3.14159265])

### 특별한 형태의 배열 생성

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.eye(3) # 단위 행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 배열의 데이터 타입 변환

In [51]:
# 문자열이 원소인 배열 생성
e1 = np.array(['1.5', '0.62', '2', '3.14', '3.141592'])
e1

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [52]:
# 배열을 생성할 때부터 값의 종류를 지정할 수 있음
e2 = np.array([1, 2, 3, 4, 5], dtype = 'U')
e2.dtype

dtype('<U1')

In [53]:
e2.astype('int32')

array([1, 2, 3, 4, 5])

In [54]:
e2.dtype

dtype('<U1')

In [57]:
# astype() 함수로 타입을 바꾼 후 새로운 변수에 저장을 해야 함.
new_e2 = e2.astype('int32')

In [58]:
new_e2.dtype

dtype('int32')

In [66]:
new_e1 = e1.astype(float)
new_e1

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592])

In [68]:
e3 = np.array([1, 2, 3, 4, 5])
e3.dtype

dtype('int32')

In [69]:
new_e3 = e3.astype(float)
new_e3

array([1., 2., 3., 4., 5.])

In [70]:
new_e3.dtype

dtype('float64')

In [72]:
e4 = np.array([1.2, 3.54, 2.1, 6.66])
e4

array([1.2 , 3.54, 2.1 , 6.66])

In [73]:
new_e4 = e4.astype(int)
new_e4

array([1, 3, 2, 6])

### 난수 배열의 생성

In [75]:
# rand_num = np.random.rand([d0, d1, d2, ..., dn]) -> [0, 1) 사이의 실수 난수를 갖는 배열 생성
# [d0, d1, d2, ..., dn] 형태의 배열
np.random.rand(2, 3) 

array([[0.72914849, 0.76608267, 0.44899865],
       [0.95056426, 0.50129297, 0.85017718]])

In [76]:
np.random.rand()

0.6656707238750921

In [77]:
np.random.rand(2, 3, 4)

array([[[0.97159884, 0.07443664, 0.10604956, 0.89942357],
        [0.51767537, 0.14891684, 0.76964248, 0.13154616],
        [0.60364708, 0.47222411, 0.7110987 , 0.7868713 ]],

       [[0.09531242, 0.98832205, 0.03798115, 0.47444558],
        [0.83696527, 0.98095104, 0.35944164, 0.83014841],
        [0.46080729, 0.42466301, 0.59524082, 0.44117222]]])

In [78]:
# rand_num = np.random.randint([low, ] high [,size]) -> [low, high) 사이의 정수 난수를 갖는 배열 생성
np.random.randint(10, size = (3, 4))

array([[8, 6, 9, 8],
       [5, 4, 3, 4],
       [9, 6, 1, 8]])

In [79]:
np.random.randint(10)

7

In [80]:
np.random.randint(1, 10)

8

## 배열의연산

### 기본 연산

In [82]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [83]:
arr1 + arr2

array([11, 22, 33, 44])

In [84]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [85]:
arr2 * 2

array([2, 4, 6, 8])

In [87]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [88]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [89]:
arr1 / arr2

array([10., 10., 10., 10.])

In [90]:
arr1 / (arr1 ** 2)

array([0.1       , 0.05      , 0.03333333, 0.025     ])

In [91]:
arr1 > 20

array([False, False,  True,  True])

### 통계를 위한 연산

In [92]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [93]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [94]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [95]:
[arr3.min(), arr3.max()]

[0, 4]

In [96]:
arr4 = np.arange(1, 5)

In [99]:
arr4.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [100]:
arr4.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

### 행렬 연산

In [101]:
import math
math.sqrt(5)

2.23606797749979

In [102]:
A = np.array([0, 1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [104]:
B = np.array([3, 2, 0, 1]).reshape(2, 2)
B

array([[3, 2],
       [0, 1]])

In [150]:
# 행렬곱
A.dot(B)

array([[0, 1],
       [6, 7]])

In [106]:
np.dot(A, B)

array([[0, 1],
       [6, 7]])

In [107]:
# 전치행렬
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [110]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [111]:
# 역행렬
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [112]:
# 행렬식
np.linalg.det(A)

-2.0

## 배열의 인덱싱과 슬라이싱

### 배열의 인덱싱

In [113]:
# 인덱싱(indexing): 배열의 위치나 조건을 지정해 배열의 원소 선택하는 것
# 배열명[위치]
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [114]:
a1[0]

0

In [115]:
a1[4]

40

In [116]:
a1[5] = 100
a1

array([  0,  10,  20,  30,  40, 100])

In [117]:
# 배열명[위치1, 위치2, ...., 위치n]
a1[[1, 3, 5]]

array([ 10,  30, 100])

In [118]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [119]:
a2[0, 2]

30

In [120]:
a2[1]

array([40, 50, 60])

In [123]:
a2[1, 2] = 55
a2

array([[10, 20, 30],
       [40, 50, 55],
       [70, 80, 90]])

In [124]:
a2[1] = np.array([1, 2, 3])
a2

array([[10, 20, 30],
       [ 1,  2,  3],
       [70, 80, 90]])

In [126]:
a2[0] = [30, 40, 50]
a2

array([[30, 40, 50],
       [ 1,  2,  3],
       [70, 80, 90]])

In [127]:
a2[[0, 2], [0, 1]]

array([30, 80])

In [128]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [129]:
# 배열명[조건]
a[a > 3]

array([4, 5, 6])

In [130]:
a[a % 2 == 0]

array([2, 4, 6])

### 배열의 슬라이싱

In [ ]:
# 슬라이싱(slicing): 범위를 지정해 배열의 원소를 선택하는 것

In [131]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [132]:
b1[:3]

array([ 0, 10, 20])

In [133]:
b1[2:]

array([20, 30, 40, 50])

In [134]:
b1[2:4] = [7, 77]
b1

array([ 0, 10,  7, 77, 40, 50])

In [136]:
b1[3:5] = 4
b1

array([ 0, 10,  7,  4,  4, 50])

In [137]:
b2 = np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [138]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [139]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [140]:
b2[1][0:2]

array([40, 50])

In [142]:
b2[0:2, 1:3] = np.arange(1, 5).reshape(2, 2)
b2

array([[10,  1,  2],
       [40,  3,  4],
       [70, 80, 90]])

In [144]:
b2[0:2, 1:3] = np.array([[20, 30], [60, 70]])
b2

array([[10, 20, 30],
       [40, 60, 70],
       [70, 80, 90]])

In [145]:
a = np.array([10, 20, 30, 40])
a
np.append(a, 50)

array([10, 20, 30, 40, 50])

In [148]:
np.append(a, [1, 2, 3])

array([10, 20, 30, 40,  1,  2,  3])